services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASS}
      POSTGRES_DB: ${DB_POSTGRES_DB}
    ports:
      - "5432:5432"